version: "3.8"

services:
  backend:
    build: ./code/src/Backend
    ports:
      - "5000:5000"
    volumes:
      - ./code/src/Backend:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build: ./code/src/Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./code/src/Frontend:/app
    depends_on:
      - backend
    restart: unless-stopped
